version: "3.8"

services:
  app:
    image: circodelsol:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - reverse_proxy
    deploy:
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=reverse_proxy"
        - "traefik.http.routers.circodelsol.entrypoints=websecure"
        - "traefik.http.routers.circodelsol.rule=Host(`circodusol.glud.org`)"
        - "traefik.http.routers.circodelsol.service=circodelsol"
        - "traefik.http.services.circodelsol.loadbalancer.server.port=8080"
        - "traefik.http.routers.circodelsol.tls=true"
        - "traefik.http.routers.circodelsol.tls.certresolver=production"
  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true

volumes:
  postgres_data:
