  version: '3.8'
  services:
    app:
      build: .
      ports:
        - "8080:8080"
      env_file: 
        - .env
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
        SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
      depends_on:
        - db

    db:
      image: postgres:latest
      env_file:
        - .env
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

  volumes:
    postgres_data:
