version: '3.8'

services:
  app:
    image: circodelsol:latest
    ports:
      - "8081:8080" 
    env_file:
      - .env
    environment:
        SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/circodelsol"
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: password
        SPRING_APPLICATION_NAME: CircoDelSol
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - reverse_proxy

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external:
      name: reverse_proxy

volumes:
  postgres_data:
