version: "3.3"

services:
  app:
    image: circodelsol:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
        SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/circodelsol"
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: password
        SPRING_APPLICATION_NAME: circodelsol
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - reverse_proxy
    deploy:
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=reverse_proxy"
        - "traefik.http.routers.circodelsol.entrypoints=websecure"
        - "traefik.http.routers.circodelsol.rule=Host(`circodelsol.glud.org`)"
        - "traefik.http.routers.circodelsol.service=circodelsol"
        - "traefik.http.services.circodelsol.loadbalancer.server.port=8080"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.tls.certresolver=production"  
  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true

volumes:
  postgres_data:
